### ISSUE TITLE
Comparisons that involve a possible error

### ISSUE THREAD

**Issue by adah1972** [TartanLlama/expected#10]
As I mentioned last time, I do not think it good to make functions like `operator<(const expected& lhs, const expected& rhs)` return a simple `bool`, if an error might be present. Some potential alternatives for discussion:

- Change the return type to `expected<bool, error_exists>`, where `error_exists` is a special new type. This is what I proposed last time.
- Change the return type to `std::optional<bool>`. It is similar to the previous proposal, but can be implemented in a simpler way. The drawback is the requirement of a C++17 compiler.
- Do not change the return type, but a new `error_exists` exception should be thrown when either `lhs` or `rhs` contains an error.

For broad applicability, I do not prefer the middle approach. The first option conforms to the `expected` rationale, but makes the client code a bit less straightforward. The last approach allows the most straightforward usage, but it seems a bit weird under the context of `expected`.

There is another view angle, though. If we take into account "concepts", which will likely make into C++20, a **Regular** object should be **EqualityComparable**, which requires that `==` and `!=` can work and result in a type that can be converted to `bool` implicitly. Another concept, **StrictTotallyOrdered**, requires operators like `<`, and that the result should be convertible to `bool`. Neither of the first two options can satisfy these requirements, which would make the `expected` type **Semiregular** at best. For future safety, I think comparison operators involving `expected` objects should return `bool` but may throw. We may provide alternative functions (not operators) like `tl::eq` and `tl::gte`, which return an `expected` object and will *not* throw (if value comparison does not throw).

What do you think?

**Comment by adah1972** [comment]
If we took the no-throw-in-alternative approach, we could include policy-based design and make the return type even more versatile. We can take into two aspects (for what I can think of currently):

- Whether errors are less than regular values or greater than regular values.
- Whether errors are comparable to other errors.

The final implementation could look like:

```cpp
enum error_and_value_order_t {
  error_is_smaller_than_value,
  error_is_larger_than_value,
  error_and_value_do_not_compare
};

enum error_order_t {
  error_has_order,
  error_has_no_order
};

enum class comparison_error {
  error_is_compared_with_value,
  error_is_compared_with_error
};

template <error_and_value_order_t error_and_value_order_aspect = error_and_value_do_not_compare,
          error_order_t error_order_aspect = error_has_no_order>
struct expected_comparison;

template <>
struct expected_comparison<error_is_smaller_than_value, error_has_order> {
  template <class T, class E, class U, class F>
  constexpr bool lt(const expected<T, E> &lhs, const expected<U, F> &rhs) {
    return (lhs.has_value() != rhs.has_value())
               ? (!lhs.has_value() ? true : false)
               : (!lhs.has_value() ? lhs.error() < rhs.error() : *lhs < *rhs);
  }
  …
};

…

template <>
struct expected_comparison<error_and_value_do_not_compare, error_has_no_order> {
  template <class T, class E, class U, class F>
  constexpr expected<bool, comparison_error> lt(const expected<T, E> &lhs,
                                                const expected<U, F> &rhs) {
    if (lhs.has_value() && rhs.has_value())
      return lhs < rhs;
    if (lhs.has_value() || rhs.has_value())
      return make_unexpected(comparison_error::error_is_compared_with_value);
    else
      return make_unexpected(comparison_error::error_is_compared_with_error);
  }
  …
};

…
```

**Comment by adah1972** [comment]
Some more observations:

- `std::optional` has `operator<` etc. similar to your current implementation. So your code's behaviour is kind of expected, except for the difficulty of comparing orders of errors.
- p0323r3 describes `operator==` and `operator!=`, but not `operator<`, `operator>`, `operator<=`, or `operator>=`.

I think a simple solution may be stick to p0323r3 for comparison operators? We can still define policy-based comparison classes as extensions.

**Comment by TartanLlama** [comment]
I think you're right that the easiest solution is to stick to p0323r4 and possibly define ordering classes as extensions later.
