### ISSUE TITLE
Macros redefined

### ISSUE THREAD

**Issue by seanfisk** [TartanLlama/expected#12]
Thanks for creating optional and expected! I like them so much I'm using both in the same project.

However, when both headers are included together, three macros get redefined:
- `IS_TRIVIALLY_COPY_CONSTRUCTIBLE`
- `IS_TRIVIALLY_COPY_ASSIGNABLE`
- `IS_TRIVIALLY_DESTRUCTIBLE`

To address this, the macros could be defined to be unique to each project or wrapped with `ifndef`.

What do you think? Thanks for considering!

**Comment by TartanLlama** [comment]
Thanks for the report! I've renamed them to `TL_[EXPECTED/OPTIONAL]_IS_...` in the most recent commits.
