### ISSUE TITLE
operator== fails to compile if T is void

### ISSUE THREAD

**Issue by Crzyrndm** [TartanLlama/expected#121]
See https://godbolt.org/z/ahczYWWEf

The std::expected docs for [operator==](https://en.cppreference.com/w/cpp/utility/expected/operator_cmp) cover this with the second overload I believe (T is void. No comparison is made against the "value")

**Comment by TartanLlama** [comment]
Fixed by https://github.com/TartanLlama/expected/commit/d901f362ccba8635951dcc9257e7bb13aff03514
