### ISSUE TITLE
Make exceptions optional

### ISSUE THREAD

**Issue by mmha** [TartanLlama/expected#15]
It would be nice to have either a preprocessor option or a separate set of functions (`unsafe_value()`?) to disable throws in `expected` and invoke undefined behavior instead because this fails to compile with gcc and the `-fno-exceptions` flag. This makes it impossible to use in constrained environments like microcontrollers and other freestanding implementations where exceptions are either too expensive or simply not implemented.

This can be implemented in standard C++ with the `noreturn` attribute [which gcc and clang can take advantage of](https://godbolt.org/g/PQVurg):
```c++
template<typename E>
[[noreturn]] constexpr void throw_exception(E &&e) {
#ifndef DISABLE_EXCEPTIONS
    throw std::forward<E>(e);
#endif
}
```

[`throw` statements are legal in [[noreturn]] functions](http://eel.is/c++draft/dcl.attr.noreturn#3).

**Comment by TartanLlama** [comment]
@mmha how does that fix look?

**Comment by TartanLlama** [comment]
It should detect whether you have exceptions turned on or not automatically, so doesn't need another preprocessor option.

**Comment by mmha** [comment]
Thank you for adding this. Looks good, but you missed the `try/catch` blocks that [don't work](https://godbolt.org/g/5iTms5) with `-fno-exceptions` either

**Comment by TartanLlama** [comment]
How about now?

**Comment by TartanLlama** [comment]
@mmha have you had a try with the new updates?
