### ISSUE TITLE
.and_then() does not work with non-constexpr T

### ISSUE THREAD

**Issue by apokluda** [TartanLlama/expected#17]
First of all, thanks for sharing a great implementation an enhanced std::expected!

I ran into a problem when trying to use a type that does not have a constexpr constructor with `tl::expected<T, E>` when using `.and_then()`. Here's a minimal example that reproduces the problem:

```
#include "expected.hpp"
#include <string>

tl::expected<int, int> operation1() { return 42; }

tl::expected<std::string, int> operation2(int const val) { return "Bananas"; }

tl::expected<std::string, int> do_something()
{
	auto const intermediate_result = operation1();

	// DOES NOT COMPILE
	return intermediate_result.and_then(operation2);

	// Must do this instead
	//if (!intermediate_result)
	//	return tl::make_unexpected(intermediate_result.error());
	//return operation2(intermediate_result.value());
}
```

As noted, the line "does not compile" causes the compiler error "error C2476: 'constexpr' constructor does not initialize all members" with Visual Studio 2015 and 2017. Two workarounds that solve the issue are: 1) Remove `constexpr` from the `expected_storage_base<T, E, false, true>` constructor on line 426 of expected.hpp (not ideal), or 2) add `char dummy;` as the first member of the union in that class and then initialize `dummy` on line 426. This constructor does not explicitly initialize either union member so the compiler will default initialize the first union member; however, since this constructor is marked constexpr, the first union member must also have a constexpr constructor. The first workaround removes constexpr from the constructor so the the first union member is not required to also have a constexpr constructor, while the second workaround adds another member to the union with a constexpr constructor (default initialization for `char`). Initializing the second member of the union instead of the first is not an option since `tl::unexpected<E>()` is deleted.

I think a correct solution would be to use something like `std::aligned_storage<sizeof(T), alignof(T)>::type` in the union instead of `T` directly.

**Comment by TartanLlama** [comment]
Thanks for the detailed report! I fixed it with option 2. I can't use `std::aligned_storage<sizeof(T), alignof(T)>::type` because that would require placement new for construction, which isn't `constexpr` (yet).
