### ISSUE TITLE
expected and polymorphism

### ISSUE THREAD

**Issue by zolo** [TartanLlama/expected#23]
```
auto return_derived_type() -> expected<std::unique_ptr<derived_type>, std::error_code>
{
    ....
}
auto test() -> expected<std::unique_ptr<basetype>, std::error_code>
{
    // NO VIABLE OVERLOAD '='
    expected<std::unique_ptr<basetype>, std::error_code> res = do_something();
    ...
    return res;
}
```

Isn't there a way to convert an expected taking a derived-type unique_ptr to the basetype version?

**Comment by zolo** [comment]
I wonder if the issue is that the assignment doesn't do a std::move of the unique_ptr, as it compiles if I do it manually:

```
auto res = do_something();
std::unique_ptr<basetype> base = std::move(res.value());
...
```

**Comment by TartanLlama** [comment]
Thanks, that was a single-character bug :laughing: . Fixed.

**Comment by zolo** [comment]
@TartanLlama not so fast ;)

On line 700

object of type 'std::__1::unique_ptr<basetype, std::__1::default_delete<basetype> >' cannot be assigned because its copy assignment operator is implicitly deleted

**Comment by TartanLlama** [comment]
@zolo Can you post a compiler explorer link? This is what I tried and now works: https://godbolt.org/g/HaKMSe

**Comment by zolo** [comment]
I'm unable to produce a small test case because I'm using protobuf.

`Object of type 'std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >' cannot be assigned because its copy assignment operator is implicitly deleted`

So maybe it's something with the way google::protobuf::Message define constructors and assignment operators that's incompatible with your `expected` implementation?

**Comment by zolo** [comment]
From the standard:

_If the class definition declares a move constructor or move assignment operator, the implicitly declared copy constructor is defined as deleted_

**Comment by zolo** [comment]
Changing line 700 to

`get() = std::move(std::forward<Rhs>(rhs).get());`

works.

I added std::move.

But this probably only works because protobuf::Message has move constructor and implicitely deleted copy constructor?

Could tl::expected deal with this case using some type trait magic?

**Comment by TartanLlama** [comment]
Hmm, that change would break lvalues. Can you post the line which triggers that error?

**Comment by zolo** [comment]
Here's the compile error stack:

```
expected.hpp:700:13: Object of type 'std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >' cannot be assigned because its copy assignment operator is implicitly deleted

expected.hpp:651:6: In instantiation of function template specialization 'tl::detail::expected_operations_base<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >, std::__1::error_code>::assign_common<tl::detail::expected_operations_base<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >, std::__1::error_code> &>' requested here

expected.hpp:917:11: In instantiation of function template specialization 'tl::detail::expected_operations_base<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >, std::__1::error_code>::assign<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >, nullptr>' requested here

expected.hpp:1406:47: In instantiation of member function 'tl::detail::expected_move_assign_base<std::__1::unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >, std::__1::error_code, false>::operator=' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2394:3: Copy assignment operator is implicitly deleted because 'unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >' has a user-declared move constructor

memory:2394:3: Copy assignment operator is implicitly deleted because 'unique_ptr<google::protobuf::Message, std::__1::default_delete<google::protobuf::Message> >' has a user-declared move constructor
```

This is clang-902.0.39.1 on macOS.

Extract of code that causes the issue:

```
auto doit() -> expected<std::unique_ptr<SubclassOfProtobufMessage>, std::error_code>
{
	...
}

// Error triggered by:
expected<std::unique_ptr<google::protobuf::Message>, std::error_code> msg = doit();
```

Here's the protobuf declaration for Message:
https://github.com/google/protobuf/blob/master/src/google/protobuf/message.h#L189

**Comment by TartanLlama** [comment]
Aha, I see the problem, there's a `std::move` missing in a function which calls that. Thanks! Try the latest version.

**Comment by TartanLlama** [comment]
TODO: make a minimal test to reproduce this and add to the test suite

**Comment by zolo** [comment]
Yeah, was about to ask for a test to cover this ;)

Thanks a lot, everything works for me now.

**Comment by zolo** [comment]
Interesting, clang on Linux doesn't seem to like the conversion from unique_ptr to expected<unique_ptr>

```
 error: no viable conversion from returned value of type 
 'std::__1::unique_ptr<MyType, std::__1::default_delete<MyType> >' 
 to function return type 
 'tl::expected<std::__1::unique_ptr<MyType, std::__1::default_delete<MyType> >, std::__1::error_code>') ```

**Comment by TartanLlama** [comment]
Test added.

**Comment by zolo** [comment]
You mean the explicit std::move is no longer needed?

**Comment by TartanLlama** [comment]
At least I can't reproduce it anymore. If you have an example and compiler version which fails I can have another look :)
