### ISSUE TITLE
Moving expected doesn't work for nested types

### ISSUE THREAD

**Issue by kkaefer** [TartanLlama/expected#29]
It seems like this implementation of `expected` is unable to select the move constructor on GCC >= 5 for types that are more complex. While this compiles without issue:

```cpp
#include <expected.hpp>

struct Foo {
    Foo() {}
    Foo(Foo&) = delete;
    Foo(Foo&&) {}
};

tl::expected<Foo, std::exception_ptr> bar() {
    Foo foo;
    return { std::move(foo) };
}
```

adding `std::vector` (which has move constructors as well) into the mix will make it fail on GCC >= 5. It compiles fine on Clang, and GCC 4.9.

```cpp
#include <expected.hpp>
#include <vector>

struct Foo {
    Foo(Foo&) = delete;
    Foo(Foo&&) {}
};

tl::expected<std::vector<Foo>, std::exception_ptr> bar() {
    std::vector<Foo> foos;
    return { std::move(foos) };
}
```

**Comment by TartanLlama** [comment]
This seems to be because GCC's `__is_trivially_constructible` instantiates the copy-constructor for `std::vector<Foo>` in an SFINAE-unfriendly manner, causing a hard error. I'll see if I can find a workaround.

**Comment by TartanLlama** [comment]
Ah, it's because `std::vector` still defines a copy constructor, even if the underlying type is not copy-constructible. Hmm. I suspect I might need an icky workaround which tests `::value_type` on containers or something.

**Comment by TartanLlama** [comment]
Interestingly this is fixed in GCC8: https://godbolt.org/g/Mev1ik

**Comment by TartanLlama** [comment]
Looks like this commit fixed it: https://github.com/gcc-mirror/gcc/commit/b4d90ee21694777d1558cc9d2d29ac82cb7b168c

Here's a relevant bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70472

**Comment by TartanLlama** [comment]
I pushed a fix for the `std::vector` case. It's pretty awful, but I've asked on the GCC bug if there's a better workaround. Let me know if this works for you.

**Comment by TartanLlama** [comment]
Note that you'll need to `#include <vector>` _before_ `#include`ing expected, as I don't want to force all users with an affected compiler to `#include <vector>`.

**Comment by kkaefer** [comment]
Thanks for the fix! However, I wasn't looking for a `std::vector`-specific solution (we use various different types). I switched to https://github.com/martinmoene/expected-lite  which didn't have this issue.

**Comment by TartanLlama** [comment]
Cool, if you don't need the performance benefit of propagating triviality then that should work fine!

**Comment by kkaefer** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80654 could be related too
