### ISSUE TITLE
Usage Issue

### ISSUE THREAD

**Issue by rodolfo-picoreti** [TartanLlama/expected#36]
Hi, I am trying to use this library but I am having some compilations errors. I tested on **gcc 4.8**, **gcc 5.4**, **gcc 5.5** and  **gcc 6.4**  using the gcc docker image for each version. I was able to compile the following source code only on **gcc 4.8**.

The source file:
```c++
 #include "expected.hpp"
 int main() {}
```

Build Command:
```bash
g++ source.cpp -std=c++11
```

Compilation Errors:
> expected.hpp:94:3: error: 'is_trivially_copy_constructible' is not a member of 'tl::detail'
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:814:32: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>            bool = is_void_or<T, TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T)>::
>                                 ^
> expected.hpp:94:3: note: suggested alternative:
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:814:32: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>            bool = is_void_or<T, TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T)>::
>                                 ^
> In file included from service.cpp:31:0:
> /usr/local/include/c++/5.4.0/type_traits:1336:12: note:   'std::is_trivially_copy_constructible'
>      struct is_trivially_copy_constructible
>             ^
> In file included from service.cpp:32:0:
> expected.hpp:94:3: error: 'is_trivially_copy_constructible' is not a member of 'tl::detail'
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:814:32: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>            bool = is_void_or<T, TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T)>::
>                                 ^
> expected.hpp:94:3: note: suggested alternative:
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:814:32: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>            bool = is_void_or<T, TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T)>::
>                                 ^
> In file included from service.cpp:31:0:
> /usr/local/include/c++/5.4.0/type_traits:1336:12: note:   'std::is_trivially_copy_constructible'
>      struct is_trivially_copy_constructible
>             ^
> In file included from service.cpp:32:0:
> expected.hpp:94:48: error: template argument 2 is invalid
>    tl::detail::is_trivially_copy_constructible<T>
>                                                 ^
> expected.hpp:814:32: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>            bool = is_void_or<T, TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T)>::
>                                 ^
> expected.hpp:815:15: error: 'value' in namespace '::' does not name a type
>                value &&TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(E)::value>
>                ^
> expected.hpp:822:8: error: 'expected_copy_base' is not a class template
>  struct expected_copy_base<T, E, false> : expected_operations_base<T, E> {
>         ^
> expected.hpp:94:3: error: 'is_trivially_copy_constructible' is not a member of 'tl::detail'
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:879:30: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>                               TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T),
>                               ^
> expected.hpp:94:3: note: suggested alternative:
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:879:30: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>                               TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T),
>                               ^
> In file included from service.cpp:31:0:
> /usr/local/include/c++/5.4.0/type_traits:1336:12: note:   'std::is_trivially_copy_constructible'
>      struct is_trivially_copy_constructible
>             ^
> In file included from service.cpp:32:0:
> expected.hpp:94:3: error: 'is_trivially_copy_constructible' is not a member of 'tl::detail'
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:879:30: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>                               TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T),
>                               ^
> expected.hpp:94:3: note: suggested alternative:
>    tl::detail::is_trivially_copy_constructible<T>
>    ^
> expected.hpp:879:30: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>                               TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T),
>                               ^
> In file included from service.cpp:31:0:
> /usr/local/include/c++/5.4.0/type_traits:1336:12: note:   'std::is_trivially_copy_constructible'
>      struct is_trivially_copy_constructible
>             ^
> In file included from service.cpp:32:0:
> expected.hpp:94:48: error: template argument 2 is invalid
>    tl::detail::is_trivially_copy_constructible<T>
>                                                 ^
> expected.hpp:879:30: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE'
>                               TL_EXPECTED_IS_TRIVIALLY_COPY_CONSTRUCTIBLE(T),
>                               ^
> expected.hpp:97:55: error: wrong number of template arguments (3, should be 2)
>  #define TL_EXPECTED_IS_TRIVIALLY_DESTRUCTIBLE(T) std::is_trivially_destructible<T>
>                                                        ^
> expected.hpp:880:30: note: in expansion of macro 'TL_EXPECTED_IS_TRIVIALLY_DESTRUCTIBLE'
>                               TL_EXPECTED_IS_TRIVIALLY_DESTRUCTIBLE(T)>>::value
>                               ^
> expected.hpp:317:76: note: provided for 'template<class T, class U> using is_void_or = tl::detail::conditional_t<std::is_void<_Tp>::value, std::integral_constant<bool, true>, U>'
>  using is_void_or = conditional_t<std::is_void<T>::value, std::true_type, U>;
>                                                                             ^
> expected.hpp:880:74: error: 'value' in namespace '::' does not name a type
>                               TL_EXPECTED_IS_TRIVIALLY_DESTRUCTIBLE(T)>>::value
>                                                                           ^
> expected.hpp:889:8: error: 'expected_copy_assign_base' is not a class template
>  struct expected_copy_assign_base<T, E, false> : expected_move_base<T, E> {
>         ^

**Comment by TartanLlama** [comment]
Thanks, there was a macro issue, fixed now.
