### ISSUE TITLE
Compilation error on MSVC 2019 Preview 3

### ISSUE THREAD

**Issue by ben-craig** [TartanLlama/expected#52]
The MSVC preview doesn't seem to like the and_then implementation

Happened with /std:c++latest /permissive-.  I haven't tested to see if it works with flags other than that.

src\common/expected.hpp(1227): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers

src\common/expected.hpp(1895): note: see reference to class template instantiation 'tl::expected<T,E>' being compiled

src\common/expected.hpp(1235): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers

src\common/expected.hpp(1243): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers

src\common/expected.hpp(1252): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers

**Comment by ben-craig** [comment]
Seems to just be an issue with /permissive-.  /std:c++latest doesn't trigger it.

I threw some code at this to try to fix things.  I got it to compile, but my solution is probably horribly flawed.  Rather than use `*this` in the trailing return type, I use `std::declval<decltype(*this)>()`.  Maybe `decltype` is even less of an evaluated context than the trailing return type already is?  I'm not sure.  This is template wizardry that I don't tinker with on a regular basis.

**Comment by TartanLlama** [comment]
Looks like I have an MSVC bug report to write, thanks!
