### ISSUE TITLE
g++-7: compile error with expected vector type depending on include order

### ISSUE THREAD

**Issue by ksdd** [TartanLlama/expected#58]
On Ubuntu 18.04 (g++-7) I got a strange compile error for this sequence of code:

`tl::expected<std::vector<char>,bool> v1; auto v2 = v1;`

The compiler complains, that copying is disabled. The strange thing is, that this error only occurs, when `vector` is included before `expected.hpp`. No error occurs, when the include order is swapped. I don't know, if this is a compiler bug or in implementation issue. I was able to reproduce the bug on [the compiler explorer web-site](https://gcc.godbolt.org/z/9zrXDt). It seems, that the bug is present in g++ 5.x - 7.x.

**Comment by TartanLlama** [comment]
Ah, it was a workaround I had for a GCC compiler bug, but the workaround was slightly wrong. Fixed now, thanks!
