### ISSUE TITLE
[question] extending and_then with parameters

### ISSUE THREAD

**Issue by therealkenc** [TartanLlama/expected#60]
Apologies in advance for the question-oriented submission. There is no bug, and `tl::expected` is awesome. I am trying to figuring out the best way to pass varadic parameters with the `and_then()` monad idiom. 

For example, from the canonical example:
```
    auto with_tie = add_bow_tie(*cropped);
    if (!with_tie) return with_tie;
```
becomes:
```
    .and_then(add_bow_tie)
```
So far so good. But in about 100% of my cases, in reality I have:
```
    auto with_tie = add_bow_tie(*cropped, tiecolor::red);
```
Which I've been addressing with a mess of code that looks like:
```
    auto add_red_bow_tie = [](const image& img) {
        return add_bow_tie(*cropped, tiecolor::red);
    }
    [...]
    .and_then(add_red_bow_tie)
``` 
What I would really like is something (?) like:
```
   .and_then(add_bow_tie, tiecolor::red)
```
But before I proceed to specialize `tl::expected`, and probably do it wrong, I was hoping someone might have some suggestions on the correct approach. Or alternatively, confirm I should just stick with all the little lambdas or `std::bind`. Note I am _absolutely_ not asking nor suggesting `tl::expected` should be changed. I am just looking to use it right.

**Comment by TartanLlama** [comment]
Seems like a reasonable extension to make if this is a common use pattern for you. One thing I would keep in mind is that with the `.and_then(f, args...)` form, then `args...` will be evaluated regardless of whether `f` will be called. So if there are some function invocations with side effects in `args...` then you'd need to use the lambda pattern instead.

**Comment by TartanLlama** [comment]
Let me know if you need a hand

**Comment by therealkenc** [comment]
Okay, that you said it is "reasonable" is good enough for me. Mostly I asked because all the little lambdas were starting to impact readability, make me think I was just missing something colossally obvious ("doing it wrong"). I'll close the issue. Thanks for the template evaluation heads up; much appreciated.
