### ISSUE TITLE
What is the idiomatic way of returning success from void function?

### ISSUE THREAD

**Issue by jackgerrits** [TartanLlama/expected#63]
Is the following snipped the idiomatic way or is there some helper or shortcut that can be used to avoid writing out the full type?
What is the performance implication of returning a void expected object compared to an option or no error wrapper?

```c++
tl::expected<void, std::string> void_func()
{
  return tl::expected<void, std::string>();
}
```

**Comment by TartanLlama** [comment]
You can default-construct the return object directly:
```
tl::expected<void, std::string> void_func()
{
  return {};
}
```

As far as performance goes, you can see the assembly difference [here](https://godbolt.org/z/MwwamZ).

**Comment by jackgerrits** [comment]
Thanks for the repsonse!

**Comment by Gerodote** [comment]
nice ... 
```
enum class unexpected_error_find_in_map {
 NotFound,
 ShitHappened
};
```
...
error: could not convert ...(function place and name )
from ‘void’ to ‘tl::expected<void, unexpected_error_find_in_map>’
