### ISSUE TITLE
VS 2019 Support?

### ISSUE THREAD

**Issue by wbuck** [TartanLlama/expected#66]
I noticed on the list of supported VC++ compilers VS 2019 was not listed. Is there any reason why this wouldn't work in VS 2019?

**Comment by JulienLopezStilla** [comment]
it isn't listed because there doesn't seem to be a CI running VS 2019.

But as far as I can tell, it seems to work fine (can't say I use all the features though)

**Comment by TartanLlama** [comment]
This is tested now
