### ISSUE TITLE
unused parameter 'e' [-Wunused-parameter] when compiling with -fno-exceptions

### ISSUE THREAD

**Issue by andijcr** [TartanLlama/expected#71]
https://github.com/TartanLlama/expected/blob/fd96e4545cc50ddfbbead177ef6594b12b210d62/include/tl/expected.hpp#L187

i get an annoying warning when compiling with -fno-exceptions, in my local copy i solved it by adding after line 190 ```(void) e;```

**Comment by wbuck** [comment]
Yeah I'm getting the same issue

**Comment by laralex** [comment]
Could I draw some attention to this issue again? It can be portably solved as simple as @wbuck suggested , but really helps in my setup without exceptions and with treating warnings as errors.
