### ISSUE TITLE
1.0.1+ release (for e.g. inclusion in conan-center-index)

### ISSUE THREAD

**Issue by hannahwhy** [TartanLlama/expected#75]
I'm submitting my [Conan recipe for `tl::expected`](https://github.com/yipdw/conan-tl-expected) to conan-center-index: https://github.com/conan-io/conan-center-index/pull/556.  If accepted, this will deprecate https://github.com/yipdw/conan-tl-expected and the name of the package will be `tl-expected/x.y.z` (no `user/channel` part required).

conan-center-index has a policy that only official releases of a package can be included in the index, and `tl::expected` 1.0.1 [fixes a bug](https://github.com/TartanLlama/expected/issues/61) that I've hit in the past.  Can a release including that bugfix be made? If there are blockers, is there anything I can do to help?

**Comment by gocarlos** [comment]
Done in cci

**Comment by gocarlos** [comment]
New link in readme should be https://conan.io/center/
