### ISSUE TITLE
Is there a way to enforce a shared pointer copy, and never a move?

### ISSUE THREAD

**Issue by aneksteind** [TartanLlama/expected#95]
I'm using `tl::expected<std::shared_ptr<MyType>, MyError>` and want to ensure that the pointer is never moved, and only copied ([for thread safety reasons](https://stackoverflow.com/a/41874953)). Is there something I can do about my type to enforce this so that I can work with the pointer in a thread-safe manner in other locations outside of the `expected` object? I'm running into a scenario where I believe the reference count is getting decremented elsewhere (in a library I don't control) while the pointer is getting moved by `expected` when I create the object.

Specifically, I'm curious about the mechanics of `tl::expected`, and would like to avoid writing a wrapper class for std::shared_ptr that deletes the move constructor or something of similar effect. I would use a mutex, but don't have the ability to do so from within other libraries, only outside

**Comment by aneksteind** [comment]
following up, I believe the solution to my problem is to do
```cpp
const std::shared_ptr<MyType> my_const_ptr {std::make_shared(...)};
tl::expected<std::shared_ptr<MyType>> my_expected = my_const_ptr;
```
thereby forcing a copy.

**Comment by OlivierSohn** [comment]
I don't think there is a thread safety issue with moving a shared pointer. The link doesn't suggest this either.
Can you be more specific as to what you think could go wrong?

**Comment by aneksteind** [comment]
You're right. What I was thinking about isn't really a concern -- the reference count should stay atomic in any case.
